### ISSUE TITLE
how start ?

### ISSUE THREAD

**Issue by isvaldo** [EastCoastProduct/pavlok-hack-api#1]
I do not see a way to start, I pavlok, and now how do I use this api .. which application?

thanks

**Comment by iblazevic** [comment]
Does this help you https://github.com/EastCoastProduct/pavlokjs

If not please elaborate a bit more, not sure what it is really about. This repo was just a small example where you could do a request to certain url which in turn shocks you for something.

pavlokjs is the library to use for pavlok api access. Pavlok will soon have new secure api so that will need modification but it should be working for now.
